# UTF Glyphs
BPP_GLYPHS[NEWLINE]=$'\n'
BPP_GLYPHS[NBS]=" "
BPP_GLYPHS[ZAP]="⚡"
BPP_GLYPHS[DOWNARROW]="↓"
BPP_GLYPHS[TOP]="╔"
BPP_GLYPHS[MIDDLE]="║"
BPP_GLYPHS[BOTTOM]="╚"
BPP_GLYPHS[OPEN]="❰"
BPP_GLYPHS[CLOSE]="❱"

